### ISSUE TITLE
Fails To Launch *solved*

### ISSUE THREAD

**Issue by GRocket-GamingGalaxy** [cryinkfly/Autodesk-Fusion-360-for-Linux#412] opened 2024-04-19 18:00 UTC
When I launch Fusion through the launch.sh it asks to check for updates but doesnt launch the app, I've changed the launcher to FusionLauncher.exe but it says this:

![Screenshot from 2024-04-19 11-59-15](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/39783400/549a7df9-3f52-433d-b462-5925365705c9)

and here is the last lines of the terminal

![Screenshot from 2024-04-19 11-59-57](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/39783400/8137362d-964f-450c-bd82-8c60fd7c9449)

- NVidia 1650Super
- Ubuntu 23.10
- Gnome 45.2

**Additional context**

**Comment by LOENS2** [comment] 2024-04-20 10:38
I have the same error. I just did a fresh install of Fusion because I somehow killed the old installation. After installing I was greeted with this error. Also, there doesn't seem to be a Fusion360.exe at the install location.

**Comment by LOENS2** [comment] 2024-04-20 10:39
This is probably a duplicate of #411.

**Closed** 2024-08-06 12:28 UTC
Labels: bug
