### ISSUE TITLE
fusion 360 linux "protein assets to a local file on disk"

### ISSUE THREAD

**Issue by dukenukemx** [cryinkfly/Autodesk-Fusion-360-for-Linux#362] opened 2023-11-13 17:54 UTC
**Describe the bug**
After a while of using Fusion 360, you can't save anything to disk.  

**To Reproduce**
Using Fusion 360 and then after a while you can't write to disk and save progress.

**Screenshots**
![fusion 360 error](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/31163475/669de18d-5f29-4298-a13c-4508423ec959)

**Desktop (please complete the following information):**
- Don't know how to view Fusion 360 version since clicking on about will just open nothing.  Often I need to use keyboard commands like Ctrl-S to save or Ctrl-O to open files.  
- Vega 56 Mesa 23.2.1 - kisak-mesa PPA
- Linux Mint 21.1
- Cinnamon
- using OpenGL-Mode

**Comment by atsen-dev** [comment] 2023-11-27 21:45
> Hi @dukenukemx, try wine-staging 8.20 and reinstall fusion from latest installer. Error with saving perished for me.

Hi, I'm on 8.20 and I installed that today but this didn't resolve the issue for me :(

**Comment by dukenukemx** [comment] 2023-11-30 22:47
> Hi @dukenukemx, try wine-staging 8.20 and reinstall fusion from latest installer. Error with saving perished for me.

I'm on wine-staging 8.21 and this still happens.  Does this use the system wide wine or a wine that it comes with?

**Comment by dukenukemx** [comment] 2023-12-02 17:15
Not sure if this works but an issue came up for Battle.net working and the solution was to use WINE_SIMULATE_WRITECOPY=1 while using the latest version of GE-Proton.  What I did because I'm lazy, is put export WINE_SIMULATE_WRITECOPY=1 in .profile then rebooted my PC.  I had to make a Christmas tree adapter and so far no issues with saving.

**Comment by poon-holder** [comment] 2023-12-14 11:48
Fresh install w/installer worked for me. so far.

**Comment by atsen-dev** [comment] 2023-12-14 11:50
> Fresh install w/installer worked for me. so far. 

Not for me a week ago.
And you can save also after some time and some work on a project ?

Van you share your config ? (wine version for example)
Maybe it can be helpful to have a working configuration

**Comment by johnny9** [comment] 2024-01-05 02:25
I continuously saw this issue with the latest wine-staging which is now at 9.0. I switched over to bottles to see if that would help and using the latest soda runner offered by bottles also had the issue. When i downgraded the running in bottles to soda 7.0-9 the issue went away. If I have time ill test to see if downgrading wine-staging fixes my non-flatpak instance.

I am running Ubuntu 22.04

**Comment by Howy-1** [comment] 2024-01-12 19:26
I have testing in the Network-Settings of Fusion360 directly "no proxy" and  "Server verification " i have changed to "No warning when accessing via an intermediate server". 
I hope, this is the correct english Translation (in German:  "Serververifizierung:  Beim Zugriff über einen Zwischenserver keine Warnung ausgeben").  
An that is the solution for me, on two different computers, even after a restart.  I was working over 1 hour, with no crash and i can always save and export my work.

I have Zorin OS 16.3 (Ubuntu-based)

**Comment by Aus-gez** [comment] 2024-01-14 01:07
I've followed @Howy-1's suggestion. So far, it's working after 40 mins of saving every few mins! That's longer than it's  ever worked for me since this problem started.

If others can confirm that this is working, that leaves 2 questions:
* Why does this fix the problem?
* How can we make this friendly for new users?

In regards to making it new-user friendly, perhaps:
* Documentation:  a panel can appear at the end of the install process recommending that new users make these setting changes. The wiki/readme can be updated to reflect this post-install fix required.
* Find some way to automatically change set these options for new installations.
* See if there is a way to resolve the cause of this networking issue in Wine or the Host OS.

Anyone got any suggestions for those last 2 points?

**Comment by atsen-dev** [comment] 2024-01-14 06:32
The best is to fix wine itself this bug is not expected to exists as it never happen on Windows
As a workaround/hotfix, maybe we can add this at end of install but without being a main solution or default solution 
Thats my pov

I'll try that and make a feedback in this thread

**Comment by atsen-dev** [comment] 2024-01-15 14:00
I can confirm the solution work ! I've tested this morning and i've let F360 opened for the entire morning and saved multiple times without issue, also when switching networks, or after resuming my laptop

Thank you @Howy-1

**Comment by dukenukemx** [comment] 2024-01-21 07:26
Seems to work for me as well.  I was able to use Fusion 360 without ever getting that error.  Doesn't make sense that changing Network-Settings fixes this.

**Comment by Tony763** [comment] 2024-02-05 20:03
With wine `9.1` Fusion sometimes won't open files and most of time won't upload them to server even with no proxy and ignored cert checking.

**Comment by ricardojlrufino** [comment] 2024-02-20 02:01
I disabled data colection and until now is working

![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/515675/e5bdca96-d802-4bf0-8829-4c88f314a97a)


Network settings.

![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/515675/646aa701-c327-4f6c-9ed0-7c92db53d3d7)

**Comment by Tony763** [comment] 2024-02-20 21:53
Hi @ricardojlrufino, does also creating Drawing from Design works for You?
![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/5598750/d2d1423b-6356-45e9-baae-65b4f4e0f1be)

**Comment by ThirtyThreeB** [comment] 2024-07-30 23:43
I have this same issue and was not able to resolve it by changing the network settings to no proxy/do not warn.  I already had all the data collection turned off.
This is on a fresh install from the script installer as of yesterday.

**Comment by ThirtyThreeB** [comment] 2024-07-31 15:38
Thank you

- I double checked that I had do not warn/no proxy
- set offline mode
- exited fusion by closing the window
- checked running processes and noted the wine exe processes listed
- ran `kill -9 $(ps aux |grep -i '\.exe' |awk '{print $2}'|tr '\n' ' ')`
- confirmed there were no exe processes running
- launched fusion
- confirmed that it started again in offline mode
- set it to online mode
- made a test file and saved it successfully

Boom!

**Closed** 2024-08-06 12:46 UTC

**Comment by cryinkfly** [comment] 2024-09-08 18:25
Thank you all! I'm currently reviewing some configuration files in Fusion. Once I identify the correct line to address this issue, I'll update the installer to include the fix, so users won't need to perform these steps manually in the future.

**Comment by cryinkfly** [comment] 2024-09-08 19:11
So I have found the part in the NMachineSpecificOptions.xml in the section "NetworkOptionGroup":

This line for Proxy-Settings:

`<WindowsProxyOptionId ToolTip=" Windows-Netzwerk-Proxy - Einstellung" UserName="Windows-Netzwerk-Proxy - Einstellung" Value="No Proxy"/></NetworkOptionGroup>`

... and this line for the server verification:

`<SSLVerifyPeerOptionId ToolTip="Stellen Sie sicher, dass der Autodesk Fusion 360-Client das Server-SSL-Zertifikat validieren kann." UserName="Serververifizierung" Value="TrustAllServers"/></NetworkOptionGroup>`

**Comment by cryinkfly** [comment] 2024-09-08 19:14
And now I just have to patch these settings into the file where the graphics card driver settings are loaded and then this bug is fixed.

Incidentally, this bug also exists under Windows and macOS and this workaround is shown by you as described above.

So this bug is not a Linux specific bug!

**Comment by cryinkfly** [comment] 2024-09-09 07:01
See: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/commit/50dc2ef91562246ac0249365dbc5e17f2d90b6cf
