### ISSUE TITLE
Fusion360 does not launch and always tries to update

### ISSUE THREAD

**Issue by Na-Cly** [cryinkfly/Autodesk-Fusion-360-for-Linux#216] opened 2022-04-19 17:52 UTC
When launching fusion360 after running the install script It tries to update, downloads the file, and then produces this error: 

0009:err:module:__wine_process_init L"C:\\windows\\system32\\.exe" not found

Here's the full output when launching and allowing it to download the update. 

--2022-04-19 13:50:30--  https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/build-version.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘/home/nacly/.config/fusion-360/bin/build-version.txt’

build-version.txt   100%[===================>]      20  --.-KB/s    in 0s      

Last-modified header missing -- time-stamps turned off.
2022-04-19 13:50:31 (2.36 MB/s) - ‘/home/nacly/.config/fusion-360/bin/build-version.txt’ saved [20/20]

Online Build-Version: 2.0.12670
cat: '/home/nacly/.wineprefixes/fusion360/drive_c/users/nacly/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/version.txt': No such file or directory
System Build-Version: 
cat: '/home/nacly/.wineprefixes/fusion360/drive_c/users/nacly/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/version.txt': No such file or directory
--2022-04-19 13:50:59--  https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe
Resolving dl.appstreaming.autodesk.com (dl.appstreaming.autodesk.com)... 23.59.99.62
Connecting to dl.appstreaming.autodesk.com (dl.appstreaming.autodesk.com)|23.59.99.62|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1102977496 (1.0G) [application/octet-stream]
Saving to: ‘Fusion360installer.exe’

Fusion360installer. 100%[===================>]   1.03G  15.1MB/s    in 63s     

2022-04-19 13:52:03 (16.7 MB/s) - ‘Fusion360installer.exe’ saved [1102977496/1102977496]

0049:err:module:__wine_process_init L"C:\\windows\\system32\\.exe" not found

**Comment by McT73** [comment] 2022-04-22 15:00
Hi all,

I'm facing a very similar behavior, excep the error message, after downloading the latest fusion 360 version the window is just closed without any error message:
_

> --2022-04-22 16:49:02--  https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/build-version.txt
> Auflösen des Hostnamens raw.githubusercontent.com (raw.githubusercontent.com) … 2606:50c0:8002::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ...
> Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443 … verbunden.
> HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
> Länge: 20 [text/plain]
> Wird in »/home/martin/.config/fusion-360/bin/build-version.txt« gespeichert.
> 
> build-version.txt   100%[===================>]      20  --.-KB/s    in 0s      
> 
> »Last-modified«-Kopfzeile fehlt -- Zeitstempel abgeschaltet.
> 2022-04-22 16:49:02 (526 KB/s) - »/home/martin/.config/fusion-360/bin/build-version.txt« gespeichert [20/20]
> 
> Online Build-Version: 2.0.12670
> cat: '/home/martin/.wineprefixes/fusion360/drive_c/users/martin/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/version.txt': Datei oder Verzeichnis nicht gefunden
> System Build-Version: 
> cat: '/home/martin/.wineprefixes/fusion360/drive_c/users/martin/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/version.txt': Datei oder Verzeichnis nicht gefunden
> --2022-04-22 16:49:20--  https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe
> Auflösen des Hostnamens dl.appstreaming.autodesk.com (dl.appstreaming.autodesk.com) … 104.90.159.145
> Verbindungsaufbau zu dl.appstreaming.autodesk.com (dl.appstreaming.autodesk.com)|104.90.159.145|:443 … verbunden.
> HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
> Länge: 1101312840 (1,0G) [application/octet-stream]
> Wird in »Fusion360installer.exe« gespeichert.
_

Any time I try to start the appliation the same procedure starts over again.

**Comment by cryinkfly** [comment] 2022-04-23 10:57
@McT73 Can you look here:

    /home/martin/.wineprefixes/fusion360/drive_c/users/martin/AppData/Roaming/Autodesk/Autodesk Fusion 360/API

if there is the version.txt. When it doesn't exists then create this file and save there current [version number](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux#current-version-of-autodesk-fusion-360)!

**Comment by Na-Cly** [comment] 2022-04-23 20:31
@cryinkfly I tried creating that file and putting in the version number, but the launch is the same every time it just reads the version number before trying to update.

**Comment by mcbb2001** [comment] 2022-04-25 01:19
I've gotten back into this after a bit of a pause for school;
I got it working a few days ago however since what I think is a new update I've been having the same issue. Another discord server that I'm in noted that they just changed the fusion360 logo so they could've had a bigger update that broke something. I'm not nearly as experienced with this so no idea what the issue could actually be, just shooting and seeing what sticks

**Comment by mcbb2001** [comment] 2022-04-25 01:20
> I've gotten back into this after a bit of a pause for school; I got it working a few days ago however since what I think is a new update I've been having the same issue. Another discord server that I'm in noted that they just changed the fusion360 logo so they could've had a bigger update that broke something. I'm not nearly as experienced with this so no idea what the issue could actually be, just shooting and seeing what sticks

One thing I did note is I looked under the directory you posted a few comments up and that directory didn't exist (not sure if that's written on first launch), and therefore version.txt didn't exist either. manually adding the directories did work

**Comment by joelawm** [comment] 2022-04-26 02:03
I had this error even after adding the version.txt, I am on pop_os 22.04 though and there is not install option for that.
```
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.7 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
002c:fixme:ver:GetCurrentPackageId (000000000066FD70 0000000000000000): stub
wine: could not open working directory L"unix\\home\\$useri\\.config\\fusion-360\\bin\\", starting in the Windows directory.
0034:fixme:ver:GetCurrentPackageId (00000000006AFD70 0000000000000000): stub
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

00f8:fixme:ver:GetCurrentPackageId (00000000006AFD70 0000000000000000): stub
003c:fixme:ver:GetCurrentPackageId (00000000006BFD70 0000000000000000): stub
```

**Comment by lukinoway** [comment] 2022-04-26 10:47
I tried to install Fusion 360 on my Fedora 35 machine, and had the same error.
adding version.txt for sure helped, but now I'm stuck with the same message as @joelawm  was mentioning.

```
wine: could not open working directory L"unix\\home\\<USER>\\.config\\fusion-360\\bin\\", starting in the Windows directory.
```

**Comment by spennydl** [comment] 2022-04-26 21:15
I'm running into this issue too and have done a little digging

I don't think the `could not open working directory` error is relevant here, rather the next line:
```
Application could not be started, or no application associated with the specified file.
```
The `launcher.sh` script runs `find` to try and locate `Fusion360.exe` as the directory name it's installed under changes from release to release. After a fresh install `Fusion360.exe` is nowhere to be found in my wineprefix, so the `find` command comes up empty.

There is a `FusionLauncher.exe`, but attempting to run that gives me an error that reads "FusionLauncher.exe.ini can't be found, please reinstall" error.

I don't have a fix, but wanted to share my findings so far. It looks like something has either changed with Fusion360 or the installation didn't complete correctly.

**Comment by JacobWarners** [comment] 2022-04-26 22:39
I ended up getting it to work and after all the tinkering I can't figure out what worked. So for me I originally had this error. Then used the uninstall to remove it from .wineprefixes and .wine which I had it in both. I then restarted the install script from the .config folder and after creating the .wine folder again I targeted it. Once this was done I had to go in and change the launcher script to point to the .wine location. I didn't have to add the update file to the location listed above as it seemed to place it properly.

#/home/martin/.wineprefixes/fusion360/drive_c/users/martin/AppData/Roaming/Autodesk/Autodesk Fusion 360/API

Randomly after a reboot and trying to just load it on a windows virtual box I just frustratedly ran it again and it worked! I was then able to design what I needed. Let me know if this helps anyone!

**Comment by joelawm** [comment] 2022-04-27 02:40
I also am missing the fusion360.exe in
`/home/$useer/.wineprefixes/fusion360/`

**Comment by 3nt3** [comment] 2022-04-27 15:43
bump, noticing the same behavior when trying to install

**Comment by Noxdor** [comment] 2022-04-28 00:20
I am running into the same issues. I tried to remove and reinstall it like @JacobWarners suggested, but unfortunately that didn't work for me.

I also looked into the from @spennydl mentioned `FusionLauncher.exe` in (for me) `/home/name/.wine/drive_c/Program Files/Autodesk/webdeploy/production/6a0c9611291d45bb9226980209917c3d`. The required `FusionLauncher.exe.ini` is right next to it, but empty besides the text `This is a place-holder file which is intended to be updated by the streamer.`.

I am also missing the `Fusion360.exe`.

Hope this helps someone with more wine knowledge to figure this out.

**Comment by spennydl** [comment] 2022-04-28 01:50
I just realized that there's already an issue open for the missing Fusion360.exe issue: #215. OP @Na-Cly appears to have a different issue with the missing system32.exe, possibly a bad wine config or install? Either way we may want to move the discussion about missing Fusion360.exe over to #215. I haven't had a chance to look at it again since yesterday but if I figure something out I'll update over there.

**Comment by cryinkfly** [comment] 2022-05-03 04:56
So I've already noticed that there are problems with some. For some it can be caused by, for example, Winetricks not being able to download the packages when the servers are being maintained. Furthermore, I noticed that the language of the system + Wine also plays an important role. In any case, I'm already working on a solution and will try to solve these problems and others with the upcoming update!

In any case, it should be said here: Thanks to everyone who supports me in my work and also helps other people here in my community!!! ❤️

**Comment by BaronVonSatchel** [comment] 2022-05-19 22:27
I think this is the same issue or closely related to #224, which was closed because the OP managed to get it working, but does not know what was actually changed that make it work. The problem seems to be the script downloads the installer, but fails to actually install F360. So when it is checking for updates, anything other than nothing at all counts as a "new version." But the installer still fails every time so it never breaks the cycle. If you try to run it manually from the command line, a graphical issue causes it to show a blank white window. This happens across both AMD and Nvidia GPUs, I don't know if anyone has tried with Intel integrated graphics.

**Comment by maximevince** [comment] 2022-05-22 10:49
Same issue here on Arch Linux.
Fusion is not actually installed (no .exe found) and the launcher script tried to update all the time.

**Comment by sipvoip** [comment] 2022-05-26 00:30
Just tried a new install on two EL8 boxes and get the same error:
--2022-05-25 20:21:32--  https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/build-version.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8001::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘/home/nathan/.config/fusion-360/bin/build-version.txt’

build-version.txt   100%[===================>]      20  --.-KB/s    in 0s      

Last-modified header missing -- time-stamps turned off.
2022-05-25 20:21:32 (3.98 MB/s) - ‘/home/nathan/.config/fusion-360/bin/build-version.txt’ saved [20/20]

Online Build-Version: 2.0.12888
cat: '/home/nathan/.wineprefixes/fusion360/drive_c/users/nathan/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/version.txt': No such file or directory
System Build-Version: 
Gtk-Message: 20:21:32.840: GtkDialog mapped without a transient parent. This is discouraged.
cat: '/home/nathan/.wineprefixes/fusion360/drive_c/users/nathan/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/version.txt': No such file or directory



I looked and I don't have an Autodesk directory in Roaming directory.

**Comment by andrewazores** [comment] 2022-05-29 14:44
```bash
$ pwd
/home/andrew/.wineprefixes/fusion360/drive_c/users/andrew/AppData/Roaming/Autodesk

$ tree
.
└── Neutron Platform
    └── Options
        └── NMachineSpecificOptions.xml

2 directories, 1 file
```

**Comment by cryinkfly** [comment] 2022-05-30 06:48
> I also looked into the from @spennydl mentioned FusionLauncher.exe in (for me) /home/name/.wine/drive_c/Program Files/Autodesk/webdeploy/production/6a0c9611291d45bb9226980209917c3d. The required FusionLauncher.exe.ini is right next to it, but empty besides the text This is a place-holder file which is intended to be updated by the streamer..

> I am also missing the Fusion360.exe.

I have now also this problem!!! It looks like so that Autodesk has some changed things!

**Comment by kristapsk** [comment] 2022-06-02 00:51
I'm having the same issue, Fusion360.exe seems to be missing (here's `bash -x launcher.sh` output):
```
...
++ find /home/user/.wineprefixes/fusion360 -name Fusion360.exe -printf '%T+ %p\n'
++ sort -r
++ sed -r 's/.+0000000000 (.+)/\1/'
++ head -n 1
+ launcher=
+ WINEPREFIX=/home/user/.wineprefixes/fusion360
+ wine ''
0178:err:module:process_init L"C:\\windows\\system32\\.exe" not found
```

**Comment by cryinkfly** [comment] 2022-06-02 09:38
Please look here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/232#issuecomment-1144487489

**Closed by cryinkfly** 2022-06-02 09:38 UTC
Labels: bug, documentation, help wanted
